import { StyleSheet } from "@react-pdf/renderer";
import { COLORS } from "./colors";

export const styles = StyleSheet.create({
  page: {
    padding: 0,
    fontSize: 8,
    fontFamily: "Helvetica",
    backgroundColor: COLORS.bg.primary,
  },
  header: {
    backgroundColor: COLORS.primary,
    padding: "10 16",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logo: {
    width: "auto",
    height: 25,
  },
  companyName: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.text.inverse,
    letterSpacing: -0.3,
  },
  companySubtitle: {
    fontSize: 6,
    color: COLORS.text.inverse,
    opacity: 0.9,
  },
  qrCode: {
    width: 45,
    height: 45,
    backgroundColor: COLORS.bg.primary,
    padding: 2,
    borderRadius: 2,
  },
  content: {
    padding: 16,
  },
  infoBar: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  infoBox: {
    flex: 1,
    backgroundColor: COLORS.bg.secondary,
    border: `0.5px solid ${COLORS.border}`,
    borderRadius: 3,
    padding: 6,
    alignItems: "center",
  },
  infoLabel: {
    fontSize: 6,
    color: COLORS.text.secondary,
    marginBottom: 2,
    textTransform: "uppercase",
  },
  infoValue: {
    fontSize: 9,
    fontWeight: "bold",
    color: COLORS.text.primary,
  },
  typeBadge: {
    backgroundColor: COLORS.secondary,
    color: COLORS.text.inverse,
    padding: "3 10",
    fontSize: 8,
    fontWeight: "bold",
    borderRadius: 2,
    textTransform: "uppercase",
  },
  confirmationHero: {
    backgroundColor: COLORS.primaryLight,
    padding: 10,
    borderRadius: 4,
    marginBottom: 10,
    // border: `1px solid ${COLORS.primary}`,
    alignItems: "center",
  },
  confirmationLabel: {
    fontSize: 7,
    color: COLORS.text.secondary,
    marginBottom: 3,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  confirmationNumber: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.primary,
    letterSpacing: 2,
  },
  statusBadge: {
    backgroundColor: COLORS.success,
    color: COLORS.text.inverse,
    padding: "2 8",
    fontSize: 6,
    fontWeight: "bold",
    borderRadius: 2,
    textTransform: "uppercase",
    marginTop: 4,
  },
  routeCard: {
    border: `0.5px solid ${COLORS.border}`,
    borderRadius: 3,
    padding: 10,
    marginBottom: 10,
  },
  routeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    paddingBottom: 6,
    borderBottom: `0.5px solid ${COLORS.border}`,
  },
  ferryName: {
    fontSize: 11,
    fontWeight: "bold",
    color: COLORS.text.primary,
  },
  operatorBadge: {
    backgroundColor: COLORS.secondary,
    color: COLORS.text.inverse,
    padding: "2 8",
    fontSize: 6,
    fontWeight: "bold",
    borderRadius: 2,
    textTransform: "uppercase",
  },
  routeVisual: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    backgroundColor: COLORS.bg.secondary,
    padding: 8,
    borderRadius: 3,
    gap: 10,
  },
  location: {
    alignItems: "center",
  },
  locationName: {
    fontSize: 12,
    fontWeight: "bold",
    color: COLORS.text.primary,
  },
  locationCode: {
    fontSize: 6,
    color: COLORS.text.secondary,
    marginTop: 1,
  },
  arrow: {
    fontSize: 14,
    color: COLORS.primary,
    marginHorizontal: 8,
  },
  scheduleRow: {
    flexDirection: "row",
    gap: 8,
    paddingTop: 6,
    borderTop: `0.5px solid ${COLORS.border}`,
  },
  scheduleItem: {
    flex: 1,
  },
  scheduleLabel: {
    fontSize: 6,
    color: COLORS.text.secondary,
    marginBottom: 2,
    textTransform: "uppercase",
  },
  scheduleValue: {
    fontSize: 8,
    fontWeight: "bold",
    color: COLORS.text.primary,
  },
  pnrBox: {
    backgroundColor: COLORS.primaryLight,
    padding: "5 8",
    borderRadius: 2,
    marginTop: 6,
    alignItems: "center",
  },
  pnrText: {
    fontSize: 6,
    color: COLORS.text.secondary,
    marginBottom: 1,
  },
  pnrValue: {
    fontSize: 11,
    fontWeight: "bold",
    color: COLORS.primary,
    letterSpacing: 1.5,
  },
  activityCard: {
    border: `0.5px solid ${COLORS.border}`,
    borderRadius: 3,
    padding: 10,
    marginBottom: 10,
  },
  activityName: {
    fontSize: 11,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginBottom: 6,
  },
  activityDetail: {
    fontSize: 7,
    color: COLORS.text.secondary,
    marginBottom: 2,
  },
  sectionTitle: {
    fontSize: 9,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginBottom: 6,
    marginTop: 4,
    textTransform: "uppercase",
  },
  ferryTable: {
    border: `0.5px solid ${COLORS.border}`,
    borderRadius: 2,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: COLORS.primary,
    padding: 6,
  },
  tableHeaderCell: {
    fontSize: 6,
    fontWeight: "bold",
    color: COLORS.text.inverse,
    textTransform: "uppercase",
  },
  tableRow: {
    flexDirection: "row",
    padding: 6,
    borderBottom: `0.5px solid ${COLORS.border}`,
  },
  tableRowAlt: {
    backgroundColor: COLORS.bg.secondary,
  },
  tableCell: {
    fontSize: 7,
    color: COLORS.text.primary,
  },
  passengerList: {
    border: `0.5px solid ${COLORS.border}`,
    backgroundColor: COLORS.border,
    borderRadius: 2,
  },
  passengerItem: {
    flexDirection: "row",
    padding: 6,
    // borderBottom: `0.5px solid ${COLORS.border}`,
  },
  passengerItemAlt: {
    backgroundColor: COLORS.bg.secondary,
  },
  passengerNumber: {
    width: "10%",
    fontSize: 7,
    fontWeight: "bold",
    color: COLORS.text.primary,
  },
  passengerName: {
    width: "50%",
    fontSize: 7,
    color: COLORS.text.primary,
  },
  passengerInfo: {
    width: "40%",
    fontSize: 6,
    color: COLORS.text.secondary,
  },
  infoRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
    marginTop: 8,
  },
  infoCard: {
    flex: 1,
    backgroundColor: COLORS.bg.secondary,
    // border: `1px solid ${COLORS.border}`,
    borderRadius: 3,
    padding: 8,
  },
  cardTitle: {
    fontSize: 8,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  cardText: {
    fontSize: 7,
    color: COLORS.text.secondary,
    marginBottom: 2,
  },
  cardTextBold: {
    fontSize: 7,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginBottom: 2,
  },
  pricingBox: {
    backgroundColor: COLORS.bg.light,
    border: `0.5px solid ${COLORS.border}`,
    borderRadius: 3,
    padding: 8,
    marginBottom: 10,
  },
  pricingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
    fontSize: 7,
  },
  pricingTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 6,
    marginTop: 6,
    borderTop: `1px solid ${COLORS.primary}`,
  },
  totalLabel: {
    fontSize: 10,
    fontWeight: "bold",
    color: COLORS.text.primary,
  },
  totalAmount: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.secondary,
  },
  importantBox: {
    backgroundColor: "#FFF3E0",
    border: `0.5px solid ${COLORS.warning}`,
    borderRadius: 3,
    padding: 6,
    marginBottom: 8,
  },
  importantTitle: {
    fontSize: 7,
    fontWeight: "bold",
    color: COLORS.warning,
    marginBottom: 3,
  },
  importantText: {
    fontSize: 6,
    color: COLORS.text.primary,
    lineHeight: 1.3,
    marginBottom: 1,
  },
  termsBox: {
    backgroundColor: COLORS.bg.secondary,
    border: `0.5px solid ${COLORS.border}`,
    borderRadius: 3,
    padding: 6,
  },
  termsTitle: {
    fontSize: 7,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginBottom: 3,
  },
  termItem: {
    fontSize: 5.5,
    color: COLORS.text.secondary,
    lineHeight: 1.4,
    marginBottom: 1,
    paddingLeft: 6,
  },
  footer: {
    position: "absolute",
    bottom: 10,
    left: 16,
    right: 16,
    paddingTop: 6,
    borderTop: `0.5px solid ${COLORS.border}`,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: {
    fontSize: 5.5,
    color: COLORS.text.secondary,
  },
});
