/**
 * Image to Base64 Converter Script
 * Converts images from public folder to base64 for PDF generation
 *
 * Usage:
 * node scripts/convertImagesToBase64.js
 */

const fs = require('fs');
const path = require('path');

// Image paths to convert - UPDATED with actual file locations
const IMAGES_TO_CONVERT = {
  // Company logos - Using converted PNG from SVG (react-pdf doesn't support SVG)
  companyLogoWhite: 'public/icons/logo-white-large.png', // Actual logo for hero header
  companyLogo: 'public/icons/logo-white-small.png', // Small logo for activity cards

  // Ferry operator logos - Using PNG for react-pdf compatibility (SVG not supported)
  makruzzLogo: 'public/icons/partners/makruzz.png',
  sealinkLogo: 'public/icons/partners/nautika.png',
  greenOceanLogo: 'public/icons/partners/greenOcean.png',

  // Activity images - MUST MATCH CLIENT PDF EXACTLY!
  // NOTE: Replace these with exact images from client PDF
  divingImage: 'public/images/activities/activitiesList/1.png', // Scuba diving
  kayakingImage: 'public/images/activities/activitiesList/2.png', // Kayaking

  // Header hero image - Use forward slashes for paths
  heroImage: 'public/images/homepage/banner/heroBanner.png',
};

function imageToBase64(imagePath) {
  try {
    const fullPath = path.join(process.cwd(), imagePath);

    // Check if file exists
    if (!fs.existsSync(fullPath)) {
      console.warn(`⚠️  File not found: ${imagePath}`);
      return null;
    }

    // Read file
    const imageBuffer = fs.readFileSync(fullPath);

    // Get file extension to determine MIME type
    const ext = path.extname(imagePath).toLowerCase();
    const mimeTypes = {
      '.png': 'image/png',
      '.jpg': 'image/jpeg',
      '.jpeg': 'image/jpeg',
      '.gif': 'image/gif',
      '.svg': 'image/svg+xml',
    };

    const mimeType = mimeTypes[ext] || 'image/png';

    // Convert to base64
    const base64 = imageBuffer.toString('base64');
    const dataUrl = `data:${mimeType};base64,${base64}`;

    console.log(`✅ Converted: ${imagePath} (${(imageBuffer.length / 1024).toFixed(2)} KB)`);

    return dataUrl;
  } catch (error) {
    console.error(`❌ Error converting ${imagePath}:`, error.message);
    return null;
  }
}

function generateConstantsFile(base64Images) {
  const template = `/**
 * PDF Image Constants
 * Base64-encoded images for PDF generation
 *
 * AUTO-GENERATED by scripts/convertImagesToBase64.js
 * Generated on: ${new Date().toISOString()}
 */

// COMPANY LOGOS
export const COMPANY_LOGO_WHITE = ${base64Images.companyLogoWhite ? `"${base64Images.companyLogoWhite}"` : `"data:image/png;base64,..." // NOT FOUND - Add manually`};

export const COMPANY_LOGO = ${base64Images.companyLogo ? `"${base64Images.companyLogo}"` : `"data:image/png;base64,..." // NOT FOUND - Add manually`};

// HEADER HERO IMAGE
export const HEADER_HERO_IMAGE = ${base64Images.heroImage ? `"${base64Images.heroImage}"` : `"data:image/jpeg;base64,..." // NOT FOUND - Add manually`};

// FERRY OPERATOR LOGOS
export const FERRY_LOGOS = {
  makruzz: ${base64Images.makruzzLogo ? `"${base64Images.makruzzLogo}"` : `"data:image/png;base64,..." // NOT FOUND`},
  sealink: ${base64Images.sealinkLogo ? `"${base64Images.sealinkLogo}"` : `"data:image/png;base64,..." // NOT FOUND`},
  greenocean: ${base64Images.greenOceanLogo ? `"${base64Images.greenOceanLogo}"` : `"data:image/png;base64,..." // NOT FOUND`},
  gonautica: ${base64Images.sealinkLogo ? `"${base64Images.sealinkLogo}"` : `"data:image/png;base64,..." // NOT FOUND`}, // Same as sealink
};

// ACTIVITY IMAGES FOR BOTTOM SECTION
export const ACTIVITY_IMAGES = {
  diving: ${base64Images.divingImage ? `"${base64Images.divingImage}"` : `"data:image/jpeg;base64,..." // NOT FOUND`},
  kayaking: ${base64Images.kayakingImage ? `"${base64Images.kayakingImage}"` : `"data:image/jpeg;base64,..." // NOT FOUND`},
  scuba: ${base64Images.divingImage ? `"${base64Images.divingImage}"` : `"data:image/jpeg;base64,..." // NOT FOUND`}, // Reuse diving
  snorkeling: ${base64Images.divingImage ? `"${base64Images.divingImage}"` : `"data:image/jpeg;base64,..." // NOT FOUND`}, // Reuse diving
};

/**
 * Helper function to get ferry logo by operator name
 */
export function getFerryLogo(operatorName: string): string | null {
  const operator = operatorName.toLowerCase();

  if (operator.includes('makruzz')) return FERRY_LOGOS.makruzz;
  if (operator.includes('sealink') || operator.includes('nautika') || operator.includes('nautica')) return FERRY_LOGOS.sealink;
  if (operator.includes('green') && operator.includes('ocean')) return FERRY_LOGOS.greenocean;
  if (operator.includes('gonautica')) return FERRY_LOGOS.gonautica;

  return null;
}

/**
 * Default activities for "Check our activities" section
 */
export const DEFAULT_ACTIVITIES = [
  {
    title: "Fun Dive at Havelock",
    price: "₹2000/adult",
    image: ACTIVITY_IMAGES.diving,
  },
  {
    title: "Kayaking at Neil Island",
    price: "₹2000/adult",
    image: ACTIVITY_IMAGES.kayaking,
  },
];
`;

  return template;
}

// Main execution
console.log('🔄 Converting images to base64...\n');

const base64Images = {};
for (const [key, imagePath] of Object.entries(IMAGES_TO_CONVERT)) {
  base64Images[key] = imageToBase64(imagePath);
}

console.log('\n📝 Generating constants file...');

const constantsContent = generateConstantsFile(base64Images);
const outputPath = path.join(process.cwd(), 'src/components/pdf/constants/pdfImages.ts');

// Create directory if it doesn't exist
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Write file
fs.writeFileSync(outputPath, constantsContent, 'utf8');

console.log(`✅ Constants file generated: ${outputPath}`);
console.log('\n✨ Done! You can now use the images in your PDF component.');
console.log('\n⚠️  Note: If any images were NOT FOUND, you need to:');
console.log('   1. Add the correct image files to your public folder');
console.log('   2. Update the paths in IMAGES_TO_CONVERT in this script');
console.log('   3. Run this script again: node scripts/convertImagesToBase64.js');
